import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{BrowserRouter,useNavigate,Routes,Route,Link}from"react-router-dom";
import{PieChart,Pie,Tooltip,ResponsiveContainer}from"recharts";
import"./style.css";

const API="http://localhost:8080",T=()=>localStorage.getItem("token");
async function api(p,o={}){let r=await fetch(API+p,{...o,headers:{"Content-Type":"application/json",...(T()?{Authorization:"Bearer "+T()}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}

function Auth({reg=false}){let n=useNavigate(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState("");
async function go(e){e.preventDefault();try{if(reg){await api("/api/auth/register",{method:"POST",body:JSON.stringify({email,password})});n("/login")}else{let d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("token",d.token);localStorage.setItem("role",d.role);n("/")}}catch(x){setErr(x.message)}}
return <div className="auth"><div className="authbox"><div className="robot">🤖</div><h1>Fake Profile AI</h1><p>Advanced bot detection platform</p><form onSubmit={go}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/>{err&&<div className="error">{err}</div>}<button>{reg?"Create Account":"Login"}</button></form><Link to={reg?"/login":"/register"}>{reg?"Already registered? Login":"Create an account"}</Link></div></div>}

function Layout({children}){let n=useNavigate(),admin=localStorage.getItem("role")==="ADMIN";return <><header><div className="brand"><span>🤖</span><div><b>Fake Profile & Bot Detector</b><small>AI Trust & Safety Platform</small></div></div><nav><Link to="/">🏠 Dashboard</Link><Link to="/analyze">🔍 Analyze Profile</Link><Link to="/history">📋 Detection History</Link><Link to="/reports">📊 Reports</Link>{admin&&<Link to="/admin">👨‍💼 Admin</Link>}<Link to="/about">ℹ️ About</Link><button className="logout" onClick={()=>{localStorage.clear();n("/login")}}>Logout</button></nav></header>{children}</>}

function Guard({children}){return T()?children:<Redirect/>}function Redirect(){let n=useNavigate();useEffect(()=>n("/login"),[]);return null}

function Dashboard(){let[s,setS]=useState({total:0,bots:0,suspicious:0,genuine:0});useEffect(()=>{api("/api/detections/stats").then(setS)},[]);let data=[{name:"Genuine",value:s.genuine},{name:"Suspicious",value:s.suspicious},{name:"Bot",value:s.bots}];return <Layout><main><div className="head"><div><small>OVERVIEW</small><h2>Security Dashboard</h2><p>Monitor profile authenticity and automated behavior.</p></div><Link className="primary" to="/analyze">+ New Analysis</Link></div><div className="stats">{[["Total Analyses",s.total,"🧾"],["Bots Detected",s.bots,"🤖"],["Suspicious",s.suspicious,"⚠️"],["Genuine",s.genuine,"✅"]].map(x=><div className="stat"><i>{x[2]}</i><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="columns"><section className="panel"><h3>Detection Distribution</h3><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={data} dataKey="value" nameKey="name" outerRadius={105} label>{data.map((x,i)=><circle key={i}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></section><section className="panel"><h3>Detection Method</h3><div className="method"><b>40%</b> Rule-based signals</div><div className="method"><b>60%</b> Random Forest ML</div><p className="muted">Genuine &lt; 40% · Suspicious 40–69% · Bot ≥ 70%</p></section></div></main></Layout>}

function Analyze(){let[f,setF]=useState({username:"",followers:0,following:0,posts:0,accountAgeDays:0,postsPerDay:0,hasProfilePicture:true,hasBio:true,repeatedComments:false,twentyFourHourActivity:false}),[r,setR]=useState(null),[err,setErr]=useState("");
let set=(k,v)=>setF(a=>({...a,[k]:v}));async function go(e){e.preventDefault();setErr("");try{setR(await api("/api/detections",{method:"POST",body:JSON.stringify(f)}))}catch(x){setErr(x.message)}}
return <Layout><main><div className="head"><div><small>AI ENGINE</small><h2>Analyze Profile</h2><p>Use only profile/activity data you are authorized to process.</p></div></div><section className="panel"><form onSubmit={go}><input className="full" placeholder="Username" value={f.username} onChange={e=>set("username",e.target.value)} required/><div className="fields">{["followers","following","posts","accountAgeDays","postsPerDay"].map(k=><label>{k.replace(/([A-Z])/g," $1")}<input type="number" min="0" value={f[k]} onChange={e=>set(k,+e.target.value)}/></label>)}</div><div className="checks">{[["hasProfilePicture","Profile picture"],["hasBio","Bio"],["repeatedComments","Repeated comments"],["twentyFourHourActivity","24-hour activity"]].map(x=><label><input type="checkbox" checked={f[x[0]]} onChange={e=>set(x[0],e.target.checked)}/>{x[1]}</label>)}</div>{err&&<div className="error">{err}</div>}<button className="primary wide">🔍 Analyze Profile</button></form></section>{r&&<section className="panel result"><div><small>RESULT</small><h2>{r.prediction}</h2><div className="risk">{r.riskScore}%</div><p>Overall risk</p></div><div><div className="score"><b>{r.mlProbability}%</b><span>ML probability</span></div><div className="score"><b>{r.ruleScore}%</b><span>Rule score</span></div><h3>Explainable signals</h3><ul>{r.reasons.map(x=><li>{x}</li>)}</ul></div></section>}</main></Layout>}

function History(){let[r,setR]=useState([]);useEffect(()=>{api("/api/detections/my").then(setR)},[]);return <Layout><main><div className="head"><div><small>AUDIT LOG</small><h2>Detection History</h2></div></div><section className="panel table"><table><thead><tr><th>Username</th><th>Result</th><th>Risk</th><th>ML</th><th>Date</th></tr></thead><tbody>{r.map(x=><tr><td>{x.username}</td><td><span className={"badge "+x.prediction}>{x.prediction}</span></td><td>{x.riskScore}%</td><td>{x.mlProbability}%</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section></main></Layout>}

function Reports(){let[s,setS]=useState({total:0,bots:0,suspicious:0,genuine:0});useEffect(()=>{api("/api/detections/stats").then(setS)},[]);return <Layout><main><div className="head"><div><small>REPORTING</small><h2>Reports</h2></div></div><div className="reportgrid">{Object.entries({Analyses:s.total,Bots:s.bots,Suspicious:s.suspicious,Genuine:s.genuine}).map(x=><div className="panel"><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><section className="panel"><h3>Report Summary</h3><p>Use this page for project demonstrations and add CSV/PDF export when you are ready.</p></section></main></Layout>}

function Admin(){let[s,setS]=useState(),[u,setU]=useState([]),[d,setD]=useState([]);useEffect(()=>{Promise.all([api("/api/admin/stats"),api("/api/admin/users"),api("/api/admin/detections")]).then(x=>{setS(x[0]);setU(x[1]);setD(x[2])})},[]);return <Layout><main><div className="head"><div><small>ADMINISTRATION</small><h2>Admin Console</h2></div></div>{s&&<div className="stats">{[["Users",s.users],["Detections",s.detections],["Bots",s.bots],["Suspicious",s.suspicious]].map(x=><div className="stat"><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>}<section className="panel table"><h3>Users</h3><table><thead><tr><th>Email</th><th>Role</th><th>Created</th></tr></thead><tbody>{u.map(x=><tr><td>{x.email}</td><td>{x.role}</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section><section className="panel table"><h3>Recent detections</h3><table><thead><tr><th>Username</th><th>User</th><th>Result</th><th>Risk</th></tr></thead><tbody>{d.slice(0,25).map(x=><tr><td>{x.username}</td><td>{x.user}</td><td>{x.prediction}</td><td>{x.riskScore}%</td></tr>)}</tbody></table></section></main></Layout>}

function About(){return <Layout><main><section className="panel about"><small>ABOUT THE PROJECT</small><h2>Advanced Fake Profile & Bot Detection</h2><p>React + Spring Boot + MySQL + JWT + Python FastAPI + Random Forest. The system combines explainable rules with an ML probability to produce a risk indicator.</p><div className="tags">{["React","Spring Boot","MySQL","JWT","Python","FastAPI","Random Forest","Docker"].map(x=><span>{x}</span>)}</div><h3>Architecture</h3><p><b>React → Spring Boot → Detection Engine → Python ML → MySQL</b></p><p className="note">ML output is a risk indicator, not proof that an account or person is fake.</p></section></main></Layout>}

function App(){return <Routes><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth reg/>}/><Route path="/" element={<Guard><Dashboard/></Guard>}/><Route path="/analyze" element={<Guard><Analyze/></Guard>}/><Route path="/history" element={<Guard><History/></Guard>}/><Route path="/reports" element={<Guard><Reports/></Guard>}/><Route path="/admin" element={<Guard><Admin/></Guard>}/><Route path="/about" element={<Guard><About/></Guard>}/></Routes>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);
